[package]
name = "steam-clip-exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { workspace = true }
gtk = { workspace = true }
exporter-core = { path = "./crates/core" }
eyre = { workspace = true }
futures = "0.3.32"
futures-util = "0.3.32"
debounced = "0.2.0"

[build-dependencies]
glib-build-tools = { workspace = true }
winresource = "0.1.31"

[workspace]
members = [
    "crates/core",
]

[workspace.dependencies]
eyre = "0.6.12"
adw = { version = "0.9.1", package = "libadwaita", features = ["v1_8"] }
gtk = { version = "0.11.1", package = "gtk4", features = ["v4_14"] }
glib-build-tools = "0.22.0"
